language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unrtf antiword poppler-utils libjpeg-dev tesseract-ocr abiword
  - sudo pip2 install --pre pyhwp
install:
  - pip install --timeout=30 pep8
  - pip install --timeout=30 pyflakes
  - pip install --timeout=30 -q -e .
before_script:
  - make check
script:
  - make test
