language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - make sysdeps
  - make pydeps
install:
  - pip install --timeout=60 -q -e .
before_script:
  - make check
  - python -m fulltext test
script:
  - make test
